[package]
name = "polyomino-generator"
version = "0.1.0"
authors = ["Phlosioneer <mattmdrr2@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4"
tinyvec = "1.2"